# .github/workflows/soundcloud_daily.yml
name: SoundCloud Daily

on:
  workflow_dispatch:        # اجرا دستی
  schedule:
    - cron: "0 3 * * *"     # هر روز 03:00 UTC ~ 06:30 تهران

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # توکن OAuth درایو را از Secret به فایل token.json می‌نویسیم و صحت JSON را چک می‌کنیم
      - name: Write Drive OAuth token.json
        run: |
          echo '${{ secrets.GDRIVE_TOKEN_JSON }}' > token.json
          python - <<'PY'
          import json, sys
          p = "token.json"
          try:
              with open(p, "r", encoding="utf-8") as f:
                  js = json.load(f)
              print("token.json OK, keys:", ", ".join(js.keys()))
          except Exception as e:
              print("token.json invalid:", e)
              sys.exit(1)
          PY

      - name: Run pipeline
        env:
          # SoundCloud
          SC_CLIENT_ID: ${{ secrets.SC_CLIENT_ID }}
          SC_CLIENT_SECRET: ${{ secrets.SC_CLIENT_SECRET }}

          # Google Drive / Google Sheet
          GDRIVE_TOKEN_JSON_PATH: token.json
          DRIVE_FOLDER_ID: ${{ secrets.DRIVE_FOLDER_ID }}
          GSHEET_ARTISTS_FILE_ID: ${{ secrets.GSHEET_ARTISTS_FILE_ID }}
          ARTISTS_DRIVE_FILE_ID: ${{ secrets.ARTISTS_DRIVE_FILE_ID }}

          # Telegram
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python pipeline_run.py

      - name: Upload XLSX as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: xlsx-drops
          path: outputs/*.xlsx
          if-no-files-found: warn
